version = 1

exclude_patterns = [
  "**/*copilot*",
  "**/*vscode*",
  "**/.git/*",
  "**/Application Support/*",
  "**/archive/*",
  "**/custom/plugins/*",
  "**/custom/themes/*",
  "**/node_modules/*",
  "**/package-lock.json",
  "**/t/*",
  "**/Test*",
  "**/test*"
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ['github.com/LucasLarson/"$(git rev-parse --show-toplevel | xargs basename)"']

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "standard"
  environment = ["browser"]

[[analyzers]]
name = "sql"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "autopep8"
enabled = true

[[transformers]]
name = "isort"
enabled = true

[[transformers]]
name = "standardrb"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
