enabled: true

restylers:

  - "*"

  - name: prettier-markdown
    include: ["--print-width 79"]

  - name: clang-format
    arguments: ["-style='{IndentWidth:4}'"]
    include:
    - "**/*.c"
    - "**/*.C"
    - "**/*.c++"
    - "**/*.C++"
    - "**/*.cc"
    - "**/*.CC"
    - "**/*.cp"
    - "**/*.CP"
    - "**/*.cpp"
    - "**/*.CPP"
    - "**/*.cs"
    - "**/*.cxx"
    - "**/*.CXX"
    - "**/*.h"
    - "**/*.H"
    - "**/*.h++"
    - "**/*.H++"
    - "**/*.hh"
    - "**/*.HH"
    - "**/*.hp"
    - "**/*.HP"
    - "**/*.hpp"
    - "**/*.HPP"
    - "**/*.hxx"
    - "**/*.HXX"
    - "**/*.i"
    - "**/*.I"
    - "**/*.ii"
    - "**/*.II"
    - "**/*.java"
    - "**/*.JAVA"
    - "**/*.js"
    - "**/*.JS"
    - "**/*.m"
    - "**/*.M"
    - "**/*.mi"
    - "**/*.MI"
    - "**/*.mii"
    - "**/*.MII"
    - "**/*.mm"
    - "**/*.MM"
    - "**/*.tcc"
    - "**/*.TCC"
